openapi: 3.0.3
info:
  title: Legal Advisory
  description: Legal Advisory
  version: 3.0.0
servers:
  - url: 'https://test.api.ob.banesco.com.pa/Non-ITAndNon-HREnterpriseServices/LegalAdvisory/3.0.0/'
paths:
  /v3/LegalAdviceFacility/Initiate:
    post:
      tags:
        - LegalAdviceFacility
      summary: Initiate LegalAdviceFacility
      description: Operación asociada al dominio Acct que permite crear carta promesa de un crédito.
      operationId: InitiateLegalAdviceFacility
      parameters:
        - $ref: '#/components/parameters/ClientDt'
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/ClientApp-ChannelId'
        - $ref: '#/components/parameters/ClientApp-Name'
        - $ref: '#/components/parameters/ClientApp-UserId'
        - $ref: '#/components/parameters/X-API-Key'

      requestBody:
        $ref: '#/components/requestBodies/InitiateLegalAdviceFacilityRq'

      responses:
       '200':
          $ref: '#/components/responses/InitiateLegalAdviceFacilityRs'
       '400':
          $ref: '#/components/responses/badRequest'
       '401':
          $ref: '#/components/responses/unauthorized'
       '403':
          $ref: '#/components/responses/forbidden'
       '404':
          $ref: '#/components/responses/notFound'
       '408':
          $ref: '#/components/responses/timeOut'
       '500':
          $ref: '#/components/responses/internalServerError'


  /v3/LegalAdviceFacility/Update:
    patch:
      tags:
        - LegalAdviceFacility
      summary: Update LegalAdviceFacility
      description: Operación asociada al dominio Acct que permite actualizar carta promesa de un crédito.
      operationId: UpdateLegalAdviceFacility
      parameters:
        - $ref: '#/components/parameters/ClientDt'
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/ClientApp-ChannelId'
        - $ref: '#/components/parameters/ClientApp-Name'
        - $ref: '#/components/parameters/ClientApp-UserId'
        - $ref: '#/components/parameters/X-API-Key'

      requestBody:
        $ref: '#/components/requestBodies/UpdateLegalAdviceFacilityRq'

      responses:
       '200':
          $ref: '#/components/responses/UpdateLegalAdviceFacilityRs'
       '400':
          $ref: '#/components/responses/badRequest'
       '401':
          $ref: '#/components/responses/unauthorized'
       '403':
          $ref: '#/components/responses/forbidden'
       '404':
          $ref: '#/components/responses/notFound'
       '408':
          $ref: '#/components/responses/timeOut'
       '500':
          $ref: '#/components/responses/internalServerError'


components:
  parameters:
    ### Headers ###
    ClientDt:
      name: ClientDt
      in: header
      schema:
        type: string
      required: true
    RequestId:
      name: RequestId
      in: header
      schema:
        type: string
      required: true
    ClientApp-ChannelId:
      name: ClientApp-ChannelId
      in: header
      schema:
        type: string
      required: true
    ClientApp-Name:
      name: ClientApp-Name
      in: header
      schema:
        type: string
      required: true
    ClientApp-UserId:
      name: ClientApp-UserId
      in: header
      schema:
        type: string
      required: true
    X-API-Key:
      name: X-API-Key
      in: header
      schema:
        type: string
      required: true
    ### Headers ###

  schemas:
    ### Request ###
    InitiateLegalAdviceFacilityRq:
      $ref: './Operations/InitiateLegalAdviceFacility/InitiateLegalAdviceFacilityRq.yaml'
    UpdateLegalAdviceFacilityRq:
      $ref: './Operations/UpdateLegalAdviceFacility/UpdateLegalAdviceFacilityRq.yaml'
    ### Request ###

    ### Response ###
    InitiateLegalAdviceFacilityRs:
      $ref: './Operations/InitiateLegalAdviceFacility/InitiateLegalAdviceFacilityRs.yaml'
    UpdateLegalAdviceFacilityRs:
      $ref: './Operations/UpdateLegalAdviceFacility/UpdateLegalAdviceFacilityRs.yaml'
    ### Http Response ###
    httpResponse:
      $ref: '../../commons/HttpResponses/HttpError.yaml'
    ### Http Response ###

    ### Response ###


  ### Define Relation with  Request ###
  requestBodies:
    ### Artefacts Request ###
    InitiateLegalAdviceFacilityRq:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateLegalAdviceFacilityRq'
          example:
            LegalAdviceFacility:
            - LegalAdviceFacilityAccountReference:
                AccountFacility:
                  AccountDetails:
                    ActivityType:
                      code: ""
                    Category:
                      code: ""
              LegalAdviceFacilityAssociatedParty:
              - PartyReference:
                  PartyIdentification:
                  - Identifier:
                      identifierValue: ""
              LegalAdviceFacilityCustomerReference:
              - PartyReference:
                  PartyIdentification:
                  - Identifier:
                      identifierValue: ""
                  PartyName:
                  - name: ""
                  partyType: ""
              LegalAdviceFacilityProductReference:
                creditFacilityNumber: ""
                liquidationMode: ""
              LegalAdviceFacilityReference:
              - alternateId: ""
              LegalAdviceFacilityType:
                BankingProductType:
                  productType: ""
              legalAdviceFacilityAmount: 0
              legalAdviceFacilityAutoExpiry: false
              legalAdviceFacilityCollateralType: ""
              legalAdviceFacilityCurrency: ""
              legalAdviceFacilityDescription: ""
              legalAdviceFacilityEffectiveDate: ""
              legalAdviceFacilityEventProcessing: ""
              legalAdviceFacilityExpiryDate: ""
              legalAdviceFacilityId: ""
              legalAdviceFacilityMaturityDate: ""
              legalAdviceFacilityOpeningDate: ""
              legalAdviceSelectedOption: false
            
    
    UpdateLegalAdviceFacilityRq:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateLegalAdviceFacilityRq'
          example:
            LegalAdviceFacility:
            - LegalAdviceFacilityAccountReference:
                AccountFacility:
                  AccountDetails:
                    ActivityType:
                      code: ""
                    Category:
                      code: ""
              LegalAdviceFacilityAssociatedParty:
              - PartyReference:
                  PartyIdentification:
                  - Identifier:
                      identifierValue: ""
              LegalAdviceFacilityCustomerReference:
              - PartyReference:
                  PartyIdentification:
                  - Identifier:
                      identifierValue: ""
                  PartyName:
                  - name: ""
                  partyType: ""
              LegalAdviceFacilityProductReference:
                creditFacilityNumber: ""
                liquidationMode: ""
              LegalAdviceFacilityReference:
              - alternateId: ""
              LegalAdviceFacilityType:
                BankingProductType:
                  productType: ""
              legalAdviceFacilityAmount: 0
              legalAdviceFacilityAutoExpiry: false
              legalAdviceFacilityCollateralType: ""
              legalAdviceFacilityCurrency: ""
              legalAdviceFacilityDescription: ""
              legalAdviceFacilityEffectiveDate: ""
              legalAdviceFacilityEventProcessing: ""
              legalAdviceFacilityExpiryDate: ""
              legalAdviceFacilityId: ""
              legalAdviceFacilityMaturityDate: ""
              legalAdviceFacilityOpeningDate: ""
              legalAdviceSelectedOption: false
            
    
    ### Artefacts Request ###
  ### Define Relation with  Request ###



  ### Define Relation with  Response ###
  responses:
    ### Artefacts Response ###
    InitiateLegalAdviceFacilityRs:
      description: InitiateLegalAdviceFacilityRs
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateLegalAdviceFacilityRs'
          example:
            LegalAdviceFacility:
            - LegalAdviceFacilityAssociatedParty:
              - PartyReference:
                  PartyIdentification:
                  - Identifier:
                      identifierValue: ""
              LegalAdviceFacilityReference:
              - alternateId: ""
                referenceId: ""
            
    
    UpdateLegalAdviceFacilityRs:
      description: UpdateLegalAdviceFacilityRs
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateLegalAdviceFacilityRs'
          example:
            LegalAdviceFacility:
            - LegalAdviceFacilityAssociatedParty:
              - PartyReference:
                  PartyIdentification:
                  - Identifier:
                      identifierValue: ""
              LegalAdviceFacilityReference:
              - alternateId: ""
                referenceId: ""
            
    
    ### Artefacts Responses ###

    ### Https Responses ###
    badRequest:
      description: badRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Bad Request"
            status: "FAILED"
            statusCode: "400"
            
    
    unauthorized:
      description: unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Unauthorized"
            status: "FAILED"
            statusCode: "401"
            
    
    forbidden:
      description: forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Forbidden"
            status: "FAILED"
            statusCode: "403"
            
    
    notFound:
      description: notFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Not Found"
            status: "FAILED"
            statusCode: "404"
            
    
    timeOut:
      description: timeOut
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Time Out"
            status: "FAILED"
            statusCode: "408"
            
    
    internalServerError:
      description: internalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/httpResponse'
          example:
            message: "Internal Server Error"
            status: "FAILED"
            statusCode: "500"
            
    
    ### Https Responses ###
  ### Define Relation with  Response ###

